<?
$_SESSION["flag1"];
$_SESSION["MaKhach"];
$_SESSION["Ten"];
$_SESSION["TaiKhoan"];
$_SESSION["Ho"];
$_SESSION["Ten"];
$_SESSION["Email"];
$_SESSION["CongTy"];
$_SESSION["SoDT"];
$_SESSION["SoFax"];
$_SESSION["ThanhPho"];
$_SESSION["DiaChi"];
$_SESSION["GioTinh"];
$_SESSION["quantity"];
$_SESSION["total"];
$_SESSION['security_code'];
$_SESSION["CART"];
?>